title: Numenta.org
tagline: Numenta&nbsp;Platform&nbsp;for Intelligent&nbsp;Computing<br/>(NuPIC)

baseurl: http://numenta.org

future: false

markdown: maruku
pygments: true

name: NuPIC News
description: Numenta Platform for Intelligent Computing News
